# Generated by Django 4.1.4 on 2022-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='null', upload_to='secondary/static/images', verbose_name='Miniatura'),
        ),
    ]
